name: build-and-test

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    name: Build and test on ${{matrix.os}} in ${{matrix.build-type}} mode
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash # Necessary because of the $GITHUB_WORKSPACE variable
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
